syntax = "proto3";

package message;

// 调用发送验证码的 grpc 服务
service VerifiService {
  rpc GetVerifyCode (GetVerifiRequest) returns (GetVerifiResponse) {}
}

// 请求由 GateServer 发送，仅包含要发送验证到的 email
message GetVerifiRequest {
  string email = 1;
}

// 响应由 verfi_grpc_server 返回，包含错误码、确认发送的 email、？
message GetVerifiResponse {
  int32 error = 1;
  string email = 2;
  string code = 3;
}

// 调用 status 服务器的 grpc 服务
service StatusService {
  rpc GetChatServer(GetChatServerRequest) returns (GetChatServerResponse) {}
}

// 请求由 GateServer 发送，仅包含要连接的用户的 uuid
message GetChatServerRequest {
  int32 uuid = 1;
}

// 响应由 StatusServer 返回，包含对应 ChatServer 的地址端口和验证 token
message GetChatServerResponse {
  int32 error = 1;
  string host = 2;
  string port = 3;
  string token = 4;
}